# Generated by Django 4.0.4 on 2022-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0003_remove_point_pf1_remove_point_pf2_remove_point_pf3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='pf1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Новости-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Товары и услуги-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Фото-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf4',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отзывы-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вернулся в меню-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Посмотрел истории-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf7',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Перешел на сайт или соцсеть-%'),
        ),
        migrations.AddField(
            model_name='point',
            name='pf8',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Построил маршрут-количество'),
        ),
        migrations.AlterField(
            model_name='point',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова (слово-%)'),
        ),
    ]
