# Generated by Django 4.0.4 on 2022-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0004_point_pf1_point_pf2_point_pf3_point_pf4_point_pf5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pf8',
        ),
        migrations.AddField(
            model_name='point',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова (слово-процент)'),
        ),
        migrations.AlterField(
            model_name='point',
            name='pf1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Меню-%'),
        ),
        migrations.AlterField(
            model_name='point',
            name='pf5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Посмотрел истории-%'),
        ),
        migrations.AlterField(
            model_name='point',
            name='pf6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Перешел на сайт-%'),
        ),
        migrations.AlterField(
            model_name='point',
            name='pf7',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Построил маршрут-количество'),
        ),
    ]
